# Generated by Django 4.1.7 on 2023-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_listdo_color_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdo',
            name='color_bg',
            field=models.CharField(blank=True, default='fff', max_length=100),
        ),
    ]
