# Generated by Django 4.1.7 on 2023-03-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_list_listdo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdo',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.list'),
        ),
    ]
