# Generated by Django 4.1.7 on 2023-03-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_listdo_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='create_at',
            new_name='list_create_at',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='update_at',
            new_name='list_update_at',
        ),
    ]
