# Generated by Django 4.1.7 on 2023-03-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_create_at_list_list_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdo',
            name='list',
        ),
        migrations.AddField(
            model_name='list',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.listdo'),
        ),
    ]
