# Generated by Django 4.1.7 on 2023-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_list_todo_listdo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdo',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
