# Generated by Django 4.1.7 on 2023-03-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_listdo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdo',
            name='list',
        ),
    ]
