# Generated by Django 4.1.7 on 2023-03-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_listdo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdo',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.list'),
        ),
    ]
